# Generated by Django 5.0 on 2024-02-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
