# Generated by Django 5.0 on 2024-03-31 11:22

import django.db.models.deletion
import django_resized.forms
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('price_new', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Arts & Photography', 'Arts & Photography'), ('Biographies', 'Biographies'), ('Business & Money', 'Business & Money'), ('Calendars', 'Calendars'), ("Children's Books", "Children's Books"), ('Comics', 'Comics'), ('Performance Filters', 'Performance Filters'), ('Cookbooks', 'Cookbooks'), ('Accessories', 'Accessories'), ('Education', 'Education'), ('Indoor Living', 'Indoor Living')], max_length=25)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', blank=True, length=10, max_length=30, null=True, prefix='prod', unique=True)),
                ('first_image', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, help_text='<h5 style="color:red;"><b>The first interface (size: 700x700px)</b></h5>', keep_meta=True, quality=90, scale=None, size=[700, 700], upload_to='image/')),
                ('second_image', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, help_text='<h5 style="color:red;"><b>The second interface (size: 700x700px)</b></h5>', keep_meta=True, quality=90, scale=None, size=[700, 700], upload_to='image/')),
                ('upload_book', models.FileField(blank=True, null=True, upload_to='book')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=450)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('rate', models.IntegerField(default=0)),
                ('userid', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
